# Generated by Django 3.2.12 on 2022-11-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetials', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='studentdb',
        ),
    ]
